const dummyData = [
  {
    id: 1,
    type: 'Flat',
    name: 'Sunshine Apartments',
    roomTitle: 'Luxury 2BHK Apartment',
    description: 'A spacious 2BHK apartment with modern amenities.',
    fits: 4,
    bhk: 2,
    bathrooms: 2,
    bedrooms: 2,
    kitchens: 1,
    livingRooms: 1,
    cost: 12000,
    originalCost: 15000,
    totalRooms: 3,
    availableRooms: 2,
    rating: 4.5,
    totalRating: 120,
    features: ['gym', 'pool', 'restaurant', 'wifi'],
    images: ['/assets/property-1.jpg', '/assets/property-2.jpg', '/assets/property-3.jpg','/assets/property-1.jpg','/assets/property-3.jpg'],
    videos: [],
    street: '123 Main Street',
    city: 'Bangalore',
    state: 'Karnataka',
    zipCode: '560001',
    country: 'India',
    checkInTime: '12:00 PM',
    checkOutTime: '11:00 AM',
    taxes: 500,
    isOnSale: false,
    Saleit: false,
    isDeleted: false,
    reviews: [
      {
        id: 1,
        userName: 'John Doe',
        date: '2025-01-15',
        rating: 5,
        comment: 'Great place to stay! Highly recommended.'
      },
      {
        id: 2,
        userName: 'Jane Smith',
        date: '2025-01-10',
        rating: 4,
        comment: 'Nice apartment with good amenities.'
      }
    ]
  },
  {
    id: 2,
    type: 'PG',
    name: 'Urban Stay',
    roomTitle: 'Affordable PG for Men',
    description: 'Comfortable PG accommodation with basic facilities.',
    fits: 2,
    roomSharingForPg: 2,
    isForGirls: false,
    meals: true,
    cost: 8000,
    originalCost: 8000,
    totalRooms: 10,
    availableRooms: 4,
    rating: 4.2,
    totalRating: 0,
    capacity: 2,
    features: ['gym', 'pool', 'restaurant', 'wifi'],
    images: ['/assets/property-1.jpg'],
    videos: [],
    street: '456 Park Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    zipCode: '400001',
    country: 'India',
    isOnSale: false,
    Saleit: false,
    isDeleted: false
  },
  {
    id: 3,
    type: 'Hostel',
    name: 'Green Hostel',
    roomTitle: 'Budget-Friendly Hostel',
    description: 'Affordable hostel for students and working professionals.',
    fits: 4,
    roomSharingForPg: 4,
    isForGirls: false,
    meals: false,
    cost: 5000,
    originalCost: 5000,
    totalRooms: 20,
    availableRooms: 10,
    rating: 3.8,
    totalRating: 0,
    capacity: 4,
    features: ['gym', 'pool', 'restaurant', 'wifi'],
    images: ['/assets/property-2.jpg'],
    videos: [],
    street: '789 Green Lane',
    city: 'Chennai',
    state: 'Tamil Nadu',
    zipCode: '600001',
    country: 'India',
    isOnSale: false,
    Saleit: false,
    isDeleted: false
  },
  {
    id: 4,
    type: 'Flat',
    name: 'Ocean View Apartments',
    roomTitle: 'Premium 3BHK Apartment',
    description: 'Spacious 3BHK apartment with sea view.',
    fits: 5,
    bhk: 3,
    bathrooms: 3,
    bedrooms: 3,
    kitchens: 1,
    livingRooms: 1,
    cost: 18000,
    originalCost: 18000,
    totalRooms: 4,
    availableRooms: 1,
    rating: 4.7,
    totalRating: 0,
    features: ['gym', 'pool', 'restaurant', 'wifi'],
    images: ['/assets/property-3.jpg'],
    videos: [],
    street: '101 Ocean Drive',
    city: 'Goa',
    state: 'Goa',
    zipCode: '403001',
    country: 'India',
    isOnSale: false,
    Saleit: false,
    isDeleted: false
  },
  {
    id: 5,
    type: 'PG',
    name: 'City PG',
    roomTitle: 'Cozy PG for Boys',
    description: 'Well-furnished PG with all amenities.',
    fits: 3,
    roomSharingForPg: 3,
    isForGirls: false,
    meals: true,
    cost: 7000,
    originalCost: 7000,
    totalRooms: 15,
    availableRooms: 5,
    rating: 4.0,
    totalRating: 120,
    capacity: 3,
    features: ['gym', 'pool', 'restaurant', 'wifi'],
    images: ['/assets/property-2.jpg', '/assets/property-1.jpg', '/assets/property-3.jpg'],
    videos: [],
    street: '202 City Road',
    city: 'Pune',
    state: 'Maharashtra',
    zipCode: '411001',
    country: 'India',
    isOnSale: false,
    Saleit: false,
    isDeleted: false
  }
];

export default dummyData;
